### ISSUE TITLE
First Two Scenarios Done

### ISSUE THREAD

**Issue by jbae11** [jbae11/europe_nuclear_paper#11]
[the box link](https://uofi.app.box.com/folder/25688369010)

has the first two scenarios from 1970 - 2160.

After 2030, additional PWRs are deployed to remain a steady net capacity.

Let me know if this looks good

### Scenarios:

1. Reprocessing and usage of MOX stops at 2020
2. Reprocessing continues until 2160.

**Comment by jbae11** [comment]
@katyhuff

**Comment by jbae11** [comment]
@katyhuff

**Comment by katyhuff** [comment]
You can use the "assignees" option to assign me to an issue like this. That way, the email that I get will have the content of the issue in it.

**Comment by katyhuff** [comment]
- The box folder is a little confusing. I think the name of the first folder, for example, should end with "2020" rather than "202"
- What is "final" about these scenario directories?
- What are you hoping I'll look at in particular? I'm afraid I don't have time to review every file in these directories. Do you have specific concerns, questions, or aspects you'd like to bring to my attention?

**Comment by katyhuff** [comment]
Also, in which github repository are these input files being held? ( I recognize they are in Box, but they deserve a discoverable public home as well. )

**Comment by jbae11** [comment]
### assignees
will do!

### "Final"
I realize it is only 'final' to me.. I consider them done, meaning that they  
would be used in the paper. 

### Aspects
I think I wanted a second opinion if the results  
seemed legitimate. 

### Github
I was planning to write up a ipython notebook  
after it is confirmed with you!

Hopefully that cleared things up.
Thanks

**Comment by katyhuff** [comment]
- assignees: thanks! For the record, because this is in your personal repository and not our group repository, I don't have the power to assign myself, close this issue, label it, or anything else. 
- final: This is how one ends up with folders called final_v2, final_final, etc. I discourage it. In any case, box is a great place for these results and I'm glad you put the input files in the same directories as the output. I would encourage more meaningful and careful filenames, however, to assist others (as well as your future self) sift through the files. (e.g. "number_plot.png.png" is not a particularly helpful name and has two filetype extensions).

- Aspects: Please give me a shorter summary, rather than just a dump of all inputs/outputs and results, which are too much for me to sift through quickly. Do you think the results are legitimate? Why or why not? If you were to write a test to check your analysis, what would the test be?.

- Github:  I thought the plan was to put the input files in the transition_scenarios repository as you are working on them. Not committing your work while it's happening misses the whole purpose of version controlled repositories.

**Comment by katyhuff** [comment]
Sorry to be harsh above. I'm so glad you feel like you're done these two scenarios!

**Comment by jbae11** [comment]
- assignees: Yes! I know you mentioned the paper format and how you want it managed. I think we should have that talk as a group and then come up with a solid standard!

- final: I completely understand. 

- Aspects:
The only difference between the two scenarios is that the first one (stop_rep_2010 - it's 2010 actually.. sorry) 'stopped reprocessing' (its `mixer` and `reprocessing` facilities were decommissioned) at year 2010. I think this is correctly reflected in the relatively higher quantity of tailings (tails_total_waste.png) and spent fuel mass from reactor facilities (reactor_total_waste.png). Also, the total stockpile of reprocessed uranium and the reprocessing waste stops increasing after the year 2010. Lastly, the fuel usage (total_fuel) stays the same (same demand of fuel since same number of reactors for same amount of time) except for the kind of fuel used.

- Github: Also makes sense too. Thanks for being patient. I am sorry to have you say the same things twice ( or more than twice.. heh). 

I realize that I have been slacking off with the github updates and keeping things organized.. old habits die hard I guess. I will make additional pull requests accordingly. Thanks!

**Comment by katyhuff** [comment]
> I realize that I have been slacking off ..

I would never describe you as slacking off. You're doing great. Sorry to be nitpicky!

**Comment by jbae11** [comment]
Noo seriously I think it is extremely beneficial to learn good workflow culture! Thank you for investing your time to educate me. I will get better I promise (in time)
